allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@takumi-rs/core-darwin-arm64@2.3.3'
  - '@takumi-rs/core-darwin-x64@2.3.3'
  - '@takumi-rs/core-linux-arm64-gnu@2.3.3'
  - '@takumi-rs/core-linux-arm64-musl@2.3.3'
  - '@takumi-rs/core-linux-x64-gnu@2.3.3'
  - '@takumi-rs/core-linux-x64-musl@2.3.3'
  - '@takumi-rs/core-win32-arm64-msvc@2.3.3'
  - '@takumi-rs/core-win32-x64-msvc@2.3.3'
  - '@takumi-rs/core@2.3.3'
  - '@takumi-rs/helpers@2.3.3'
